version: 0.2

phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - curl -s "https://get.sdkman.io" | bash
      - source "$HOME/.sdkman/bin/sdkman-init.sh"
      - sdk install java 21.0.0.r11-grl
      - sdk install micronaut 2.3.0
      - sdk use java 21.0.0.r11-grl
      - sdk use micronaut 2.3.0
      - gu install native-image
      - npm install
  build:
    commands:
      - echo build started on `date`
      - ./gradlew clean
      - ./gradlew buildNativeLambda
      - sls deploy